dockerfile.filename = "bsw-arm"

script = """
    cmake -B cmake-build-s32k148 -S executables/referenceApp -DBUILD_TARGET_PLATFORM="S32K148EVB" --toolchain ../../admin/cmake/ArmNoneEabi-gcc.cmake
    cmake --build cmake-build-s32k148 --target app.referenceApp -j
"""

codeFormat = false
