name: Run pytest for posix platform

on: [push, pull_request]

jobs:
    cmake-build:
      uses: ./.github/workflows/build.yml

    run-pytest-on-posix:
      runs-on: ubuntu-latest
      needs: cmake-build

      steps:

        - name: Install missing kernel module file for vcan
          run: sudo apt install linux-modules-extra-$(uname -r)

        - name: Install can kernel modules
          run: |
            sudo modprobe can
            sudo modprobe can-raw
            sudo modprobe vcan

        - name: Set up vcan0 interface
          run: |
            sudo ip link add dev vcan0 type vcan
            sudo ip link set vcan0 mtu 16
            sudo ip link set up vcan0

        - name: Show all interface info, vcan0 should be set up
          run: ip a

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Restore cached posix build
          id: restore-cached-posix-build
          uses: actions/cache/restore@v4
          with:
            path: |
              cmake-build-posix
              cmake-build-s32k148
            key: ${{ runner.os }}-cmake-posix-gcc-20-${{ hashFiles('**/*.cpp', '**/*.h',  '**/*.cmake', '**/*.txt', '**/*.c', '**/*.s') }}
            fail-on-cache-miss: true

        - name: Set up python 3.10
          if: ${{ steps.restore-cached-posix-build.outputs.cache-hit == 'true' }}
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install python dependencies for tests
          if: ${{ steps.restore-cached-posix-build.outputs.cache-hit == 'true' }}
          run: |
            pip install -r test/pyTest/requirements.txt
            cd tools/UdsTool
            pip install .

        - name: Run tests
          if: ${{ steps.restore-cached-posix-build.outputs.cache-hit == 'true' }}
          run: |
            cd test/pyTest
            pytest --target=posix
